In [1]:
import pandas as pd

In [2]:
datos = {
    "influencer": ["AnaTravel", "CarlosBeach", "SofiaLifestyle", "LuisTrips", "MarthaSun", "DiegoExplorer"],
    "likes": [1200,2300,5400,3200,4100,2800],
    "comentarios": [120,340,560,290,430,310],
    "fecha": ["2026-01-10", "2026-01-11", "2026-01-12", "2026-01-13", "2026-01-14", "2026-01-15"],
    "tipo_post": ["Foto", "Reel", "Historia", "Video", "Foto", "Reel"]
}

In [3]:
df = pd.DataFrame(datos)

In [4]:
print(df)

       influencer  likes  comentarios       fecha tipo_post
0       AnaTravel   1200          120  2026-01-10      Foto
1     CarlosBeach   2300          340  2026-01-11      Reel
2  SofiaLifestyle   5400          560  2026-01-12  Historia
3       LuisTrips   3200          290  2026-01-13     Video
4       MarthaSun   4100          430  2026-01-14      Foto
5   DiegoExplorer   2800          310  2026-01-15      Reel

In [5]:
cantidad = 1000000

In [6]:
import random

In [11]:
influencers = ["AnaTravel", "CarlosBeach", "SofiaLifestyle", "LuisTrips", "MarthaSun", "DiegoExplorer"],
tipos_post = ["Foto", "Reel", "Historia", "Video", "Foto", "Reel"]

In [13]:
datos = {
    "influencer": [random.choice(influencers) for _ in range(cantidad)],
    "likes": [random.randint(100, 50000) for _ in range(cantidad)],
    "comentarios": [random.randint(10, 5000) for _ in range(cantidad)],
    "fecha": pd.date_range(start="2025-01-01", periods=cantidad, freq="min"),
    "tipo_post": [random.choice(tipos_post) for _ in range(cantidad)],
}

In [14]:
df_grande = pd.DataFrame(datos)

In [15]:
df_grande.head()

,influencer,likes,comentarios,fecha,tipo_post
0,"[AnaTravel, CarlosBeach, SofiaLifestyle, LuisT...",13294,3312,2025-01-01 00:00:00,Reel
1,"[AnaTravel, CarlosBeach, SofiaLifestyle, LuisT...",11778,1495,2025-01-01 00:01:00,Historia
2,"[AnaTravel, CarlosBeach, SofiaLifestyle, LuisT...",6537,2477,2025-01-01 00:02:00,Foto
3,"[AnaTravel, CarlosBeach, SofiaLifestyle, LuisT...",4117,1061,2025-01-01 00:03:00,Reel
4,"[AnaTravel, CarlosBeach, SofiaLifestyle, LuisT...",631,387,2025-01-01 00:04:00,Historia

In [16]:
df_grande.shape

(1000000, 5)

In [17]:
df_grande.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   influencer   1000000 non-null  object
 1   likes        1000000 non-null  int64
 2   comentarios  1000000 non-null  int64
 3   fecha        1000000 non-null  datetime64[us]
 4   tipo_post    1000000 non-null  str
dtypes: datetime64[us](1), int64(2), object(1), str(1)
memory usage: 38.1+ MB

In [18]:
df_grande.describe()

               likes     comentarios                fecha
count  1000000.00000  1000000.000000              1000000
mean     25049.38649     2504.083990  2025-12-14 05:19:30
min        100.00000       10.000000  2025-01-01 00:00:00
25%      12571.00000     1256.000000  2025-06-23 14:39:45
50%      25065.00000     2503.000000  2025-12-14 05:19:30
75%      37511.00000     3750.000000  2026-06-05 19:59:15
max      50000.00000     5000.000000  2026-11-26 10:39:00
std      14406.33731     1440.854947                  NaN

In [19]:
df_grande["likes"].mean()

np.float64(25049.38649)

In [20]:
df_grande["likes"].max()

np.int64(50000)

In [21]:
df_grande["tipo_post"].value_counts()

tipo_post
Foto        333454
Reel        333208
Historia    167025
Video       166313
Name: count, dtype: int64